import * as fs from 'node:fs';
import { join } from 'node:path';

import { attempt } from 'es-toolkit';

import type { Result } from '../result.ts';

/**
 * Generate a TypeScript declaration file that maps package names to their types.
 *
 * Creates `.lauf/packages.d.ts` in the package directory with a global namespace
 * that ScriptContext.import() uses. Each package gets its own types file to avoid
 * conflicts in monorepos.
 */
export function generatePackageTypes(
  packageDir: string,
  packages: Record<string, string>,
): Result<void> {
  const laufDir = join(packageDir, '.lauf');
  const typesPath = join(laufDir, 'packages.d.ts');

  const [mkdirError] = attempt(() => fs.mkdirSync(laufDir, { recursive: true }));
  if (mkdirError) {
    return [mkdirError as Error, null];
  }

  const packageEntries = Object.keys(packages).toSorted();

  const content = generateTypeDeclaration(packageEntries);

  const [writeError] = attempt(() => fs.writeFileSync(typesPath, content, { encoding: 'utf-8' }));

  if (writeError) {
    return [writeError as Error, null];
  }

  return [null, undefined];
}

function generateTypeDeclaration(packageNames: readonly string[]): string {
  const registryLines = (() => {
    if (packageNames.length === 0) {
      return ['      // No packages declared'];
    }
    return packageNames.map((name) => `      '${name}': typeof import('${name}');`);
  })();

  return [
    '// This file is auto-generated by laufen. Do not edit manually.',
    '// It provides type-safe imports for packages declared in lauf.config.ts and scripts.',
    '//',
    '// To enable these types in your editor, add ".lauf" to your tsconfig.json include:',
    '// {',
    '//   "include": ["scripts", ".lauf/**/*.d.ts"]',
    '// }',
    '',
    'declare global {',
    '  namespace LaufPackages {',
    '    interface Registry {',
    ...registryLines,
    '    }',
    '  }',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
}
